
- name: Make sure that docker starts on boot
  service:
    name: docker
    enabled: yes

- name: install pip
  apt:
    name: python3-pip
    state: latest

- name: uninstall docker-py
  pip:
    name: docker-py
    state: absent

- name: install docker
  pip:
    name: docker

- name: create docker network for internal communication
  docker_network:
    name: "{{ internal_network }}"
